"""Search fields grouped by source table; keys match SQL result aliases."""
FIELD_GROUPS = {'Case Fields': [('c__case_id', 'Case Id', 'number'),
                 ('c__revision', 'Revision', 'number'),
                 ('c__case_details_id', 'Case Details Id', 'number'),
                 ('c__lob', 'Lob', 'text'),
                 ('c__mac', 'Mac', 'text'),
                 ('c__is_act_ind', 'Is Act Ind', 'text'),
                 ('c__case_type_id', 'Case Type Id', 'number'),
                 ('c__case_status', 'Case Status', 'text'),
                 ('c__case_substatus', 'Case Substatus', 'text'),
                 ('c__assigned_to', 'Assigned To', 'text'),
                 ('c__status', 'Status', 'text'),
                 ('c__created_by', 'Created By', 'text'),
                 ('c__created_dts', 'Created Dts', 'date'),
                 ('c__updated_by', 'Updated By', 'text'),
                 ('c__updated_dts', 'Updated Dts', 'date'),
                 ('case_number', 'Case Number', 'text'),
                 ('c__assigned_to_name', 'Assigned To Name', 'text'),
                 ('c__adr_ltr_sent_dt', 'Adr Ltr Sent Dt', 'date'),
                 ('c__original_due_dt', 'Original Due Dt', 'date'),
                 ('c__new_due_dt', 'New Due Dt', 'date'),
                 ('c__bill_type', 'Bill Type', 'text'),
                 ('c__adr_ltr_rcvd_dt', 'Adr Ltr Rcvd Dt', 'date'),
                 ('c__closed_dts', 'Closed Dts', 'date'),
                 ('c__rvsn_reason', 'Rvsn Reason', 'text'),
                 ('c__assigned_dt', 'Assigned Dt', 'date'),
                 ('c__reference_case_number', 'Reference Case Number', 'text'),
                 ('c__informatics_case_type', 'Informatics Case Type', 'text'),
                 ('c__ref_demand_bill', 'Ref Demand Bill', 'text'),
                 ('c__timeliness_dt', 'Timeliness Dt', 'date'),
                 ('c__adjudication_process', 'Adjudication Process', 'text'),
                 ('c__ovrd_closed_dts', 'Ovrd Closed Dts', 'text'),
                 ('c__smpl_met_dt', 'Smpl Met Dt', 'date'),
                 ('c__language', 'Language', 'text'),
                 ('c__adjudication_date', 'Adjudication Date', 'date')],
 'Case Details': [('cd__case_details_id', 'Case Details Id', 'number'),
                  ('cd__first_rcrd_rcvd', 'First Rcrd Rcvd', 'text'),
                  ('cd__last_clm_reviewed', 'Last Clm Reviewed', 'text'),
                  ('cd__closed_date', 'Closed Date', 'date'),
                  ('cd__edit_impl_dt', 'Edit Impl Dt', 'date'),
                  ('cd__edit_term_dt', 'Edit Term Dt', 'date'),
                  ('cd__smpl_clm_cnt', 'Smpl Clm Cnt', 'number'),
                  ('cd__review_clm_cnt', 'Review Clm Cnt', 'number'),
                  ('cd__review_result_code', 'Review Result Code', 'text'),
                  ('cd__close_actn_code', 'Close Actn Code', 'text'),
                  ('cd__status', 'Status', 'text'),
                  ('cd__created_by', 'Created By', 'text'),
                  ('cd__created_dts', 'Created Dts', 'date'),
                  ('cd__updated_by', 'Updated By', 'text'),
                  ('cd__updated_dts', 'Updated Dts', 'date'),
                  ('cd__dept', 'Dept', 'text'),
                  ('cd__billing_ptan', 'Billing Ptan', 'text'),
                  ('cd__rendering_ptan', 'Rendering Ptan', 'text'),
                  ('cd__state_cd', 'State Cd', 'text'),
                  ('cd__edit_number', 'Edit Number', 'text'),
                  ('cd__contract_id', 'Contract Id', 'text'),
                  ('cd__case_file_comment', 'Case File Comment', 'text'),
                  ('cd__mip_cntrl_nbr', 'Mip Cntrl Nbr', 'text'),
                  ('cd__adhoc_name', 'Adhoc Name', 'text'),
                  ('cd__cost_center', 'Cost Center', 'text'),
                  ('cd__case_file_status', 'Case File Status', 'text'),
                  ('cd__mip_mtg_date', 'Mip Mtg Date', 'date'),
                  ('cd__mip_priority_score', 'Mip Priority Score', 'text'),
                  ('cd__npi', 'Npi', 'text'),
                  ('cd__activity_code', 'Activity Code', 'text'),
                  ('cd__referral_dept', 'Referral Dept', 'text'),
                  ('cd__referral_desc', 'Referral Desc', 'text')],
 'Claim Details': [('cl__claim_details_id', 'Claim Details Id', 'number'),
                   ('cl__bene_first_name', 'Bene First Name', 'text'),
                   ('cl__bene_last_name', 'Bene Last Name', 'text'),
                   ('cl__bene_middle_name', 'Bene Middle Name', 'text'),
                   ('cl__bene_dob', 'Bene Dob', 'date'),
                   ('mbi', 'Mbi', 'text'),
                   ('claim_number', 'Claim Number', 'text'),
                   ('cl__lob', 'Lob', 'text'),
                   ('cl__hcpc_code', 'Hcpc Code', 'text'),
                   ('cl__dos_from', 'Dos From', 'date'),
                   ('cl__dos_to', 'Dos To', 'date'),
                   ('claim_status', 'Status', 'text'),
                   ('cl__created_by', 'Created By', 'text'),
                   ('cl__created_dts', 'Created Dts', 'date'),
                   ('cl__updated_by', 'Updated By', 'text'),
                   ('cl__updated_dts', 'Updated Dts', 'date'),
                   ('cl__case_id', 'Case Id', 'number'),
                   ('cl__ptan', 'Ptan', 'text'),
                   ('cl__npi', 'Npi', 'text'),
                   ('cl__hic', 'Hic', 'text'),
                   ('cl__appeals_case_re_open', 'Appeals Case Re Open', 'text'),
                   ('cl__post_mr_actual_reimb_amount', 'Post Mr Actual Reimb Amount', 'number'),
                   ('cl__pre_mr_actual_reimb_amount', 'Pre Mr Actual Reimb Amount', 'number'),
                   ('cl__error_indicator', 'Error Indicator', 'text'),
                   ('cl__mcs_or_fiss_update', 'Mcs Or Fiss Update', 'text'),
                   ('over_payment', 'Over Payment', 'number'),
                   ('cl__paid_dt', 'Paid Dt', 'date'),
                   ('cl__ract_dt', 'Ract Dt', 'date'),
                   ('cl__mcs_or_fiss_err_msg', 'Mcs Or Fiss Err Msg', 'text'),
                   ('cl__mcs_or_fiss_update_dt', 'Mcs Or Fiss Update Dt', 'date'),
                   ('cl__type_of_bill', 'Type Of Bill', 'text'),
                   ('cl__adjustment_claim_number', 'Adjustment Claim Number', 'text'),
                   ('cl__patient_status', 'Patient Status', 'number'),
                   ('cl__place_of_service_zip_code', 'Place Of Service Zip Code', 'text'),
                   ('cl__claim_refresh', 'Claim Refresh', 'text'),
                   ('cl__claim_refresh_dt', 'Claim Refresh Dt', 'date'),
                   ('cl__place_of_service_state_code', 'Place Of Service State Code', 'text'),
                   ('cl__mcs_snap_claims_ovr_txn_number',
                    'Mcs Snap Claims Ovr Txn Number',
                    'number'),
                   ('cl__mcs_snap_claims_ovr_txn_status',
                    'Mcs Snap Claims Ovr Txn Status',
                    'text')],
 'Provider Fields': [('p__provider_details_id', 'Provider Details Id', 'number'),
                     ('provider_number', 'Provider Number (PTAN)', 'text'),
                     ('p__npi', 'Npi', 'text'),
                     ('p__lob', 'Lob', 'text'),
                     ('p__jurisdiction', 'Jurisdiction', 'text'),
                     ('p__contract_id', 'Contract Id', 'text'),
                     ('p__state_cd', 'State Cd', 'text'),
                     ('p__provider_type', 'Provider Type', 'text'),
                     ('p__status', 'Status', 'text'),
                     ('p__created_by', 'Created By', 'text'),
                     ('p__created_dts', 'Created Dts', 'date'),
                     ('p__updated_by', 'Updated By', 'text'),
                     ('p__updated_dts', 'Updated Dts', 'date'),
                     ('provider_name', 'Provider Name', 'text'),
                     ('p__specialty', 'Specialty', 'text'),
                     ('p__case_details_id', 'Case Details Id', 'number')],
 'Claim Decision Fields': [('d__claim_decision_id', 'Claim Decision Id', 'number'),
                           ('d__claim_details_id', 'Claim Details Id', 'number'),
                           ('qc_review_status', 'Decision Type', 'text'),
                           ('d__decision_date', 'Decision Date', 'date'),
                           ('d__associated_dcn', 'Associated Dcn', 'text'),
                           ('d__denial_reason', 'Denial Reason', 'text'),
                           ('d__decision_remarks', 'Decision Remarks', 'text'),
                           ('qc_status', 'Status', 'text'),
                           ('reviewed_by', 'Created By', 'text'),
                           ('d__created_dts', 'Created Dts', 'date'),
                           ('d__updated_by', 'Updated By', 'text'),
                           ('d__updated_dts', 'Updated Dts', 'date'),
                           ('qc_review', 'Qc Review', 'text'),
                           ('qc_review_comment', 'Qc Review Comments', 'text'),
                           ('reviewed_dts', 'Qc Review Dts', 'date'),
                           ('d__denial_remarks', 'Denial Remarks', 'text'),
                           ('d__demand_bill', 'Demand Bill', 'text'),
                           ('d__generic_reason_code', 'Generic Reason Code', 'text'),
                           ('d__decision_pretext', 'Decision Pretext', 'text'),
                           ('d__decision_comments', 'Decision Comments', 'text')],
 'Focus Details': [('f__focus_code_details_id', 'Focus Code Details Id', 'number'),
                   ('f__case_details_id', 'Case Details Id', 'number'),
                   ('f__focus_cd_desc', 'Focus Cd Desc', 'text'),
                   ('f__focus_cd_type', 'Focus Cd Type', 'text'),
                   ('f__modifier', 'Modifier', 'text'),
                   ('f__cart_cd', 'Cart Cd', 'text'),
                   ('f__cart_topic', 'Cart Topic', 'text'),
                   ('f__rec_clms_review', 'Rec Clms Review', 'text'),
                   ('f__smpl_clm_cnt', 'Smpl Clm Cnt', 'number'),
                   ('focus_code', 'Focus Code', 'text'),
                   ('f__status', 'Status', 'text'),
                   ('f__created_by', 'Created By', 'text'),
                   ('f__created_dts', 'Created Dts', 'date'),
                   ('f__updated_by', 'Updated By', 'text'),
                   ('f__updated_dts', 'Updated Dts', 'date')]}
